apiVersion: apps/v1
kind: Deployment
metadata:
  name: some-app
spec:
  selector:
    matchLabels:
      run: some-app
  replicas: 1
  template:
    metadata:
      labels:
        run: some-app
    spec:
      containers:
      - name: some-app
        image: joeveror/some-app
        ports:
        - containerPort: 443
        - containerPort: 80