apiVersion: v1
kind: Service
metadata:
  name: some-app
  labels:
    run: some-app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: some-app